"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useAuth} from "@/components/AuthContext";
import {supabase} from "@/lib/supabase";
type Player={id:string;display_name:string};
type Friendship={id:string;sender:string;recipient:string;status:string};
type Invite={id:string;sender:string;kind:string;code:string;created_at:string};
export default function FriendsPage(){
 const {user,token,openAuthModal}=useAuth();
 const [friends,setFriends]=useState<Friendship[]>([]),[invites,setInvites]=useState<Invite[]>([]),[profiles,setProfiles]=useState<Player[]>([]);
 const [query,setQuery]=useState(""),[player,setPlayer]=useState<Player|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [code,setCode]=useState(""),[kind,setKind]=useState("challenge");
 const load=useCallback(async()=>{if(!token)return;try{const r=await fetch("/api/friends",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setFriends(d.friends);setInvites(d.invitations);setProfiles(d.profiles || []);}catch(e){setMessage(e instanceof Error?e.message:"Could not load friends");}},[token]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),15000);const channel=supabase?.channel(`friends-${user?.id}`).on("postgres_changes",{event:"*",schema:"public",table:"friendships"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"game_invitations"},()=>void load()).subscribe();return()=>{clearInterval(timer);if(channel)void supabase?.removeChannel(channel);};},[load,user?.id]);
 async function act(action:string,id:string){setBusy(true);setMessage("");try{const r=await fetch("/api/friends",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({action,id,kind,code})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage(action==="invite"?"Invitation sent!":"Saved.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Action failed");}finally{setBusy(false);}}
 async function search(){setBusy(true);setPlayer(null);try{const r=await fetch(`/api/friends?id=${encodeURIComponent(query.trim())}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw Error(d.error);setPlayer(d.player);setMessage(d.player?"":"No player found.");}catch(e){setMessage(e instanceof Error?e.message:"Search failed");}finally{setBusy(false);}}
 const name=(id:string)=>profiles.find(p=>p.id===id)?.display_name || id;
 if(!user)return <main className="arena-container py-12"><h1 className="text-3xl font-bold mb-4">Your friends, your arena</h1><button className="arena-btn arena-btn-primary" onClick={()=>openAuthModal("signin","/friends")}>Sign in to find friends</button></main>;
 return <main className="arena-container py-10 space-y-6"><div><p className="arena-eyebrow">Squad up</p><h1 className="text-4xl font-bold">Friends & invitations</h1></div>
 <section className="arena-card"><h2 className="font-bold">Your unique user ID</h2><p className="break-all font-mono my-3">{user.id}</p><button className="arena-btn" onClick={()=>navigator.clipboard.writeText(user.id).then(()=>setMessage("User ID copied.")).catch(()=>setMessage("Select and copy your ID above."))}>Copy ID</button></section>
 <p role="status" className="text-arena-accent">{message}</p>
 <div className="grid lg:grid-cols-2 gap-6"><section className="arena-card space-y-4"><h2 className="text-xl font-bold">Add a friend</h2><form onSubmit={e=>{e.preventDefault();void search();}} className="flex flex-wrap gap-2"><input aria-label="Friend user ID" className="arena-input flex-1 min-w-0" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Paste their user ID"/><button disabled={busy} className="arena-btn arena-btn-primary">Search</button></form>{player&&<div className="flex flex-wrap justify-between gap-3"><span>{player.display_name}</span><button disabled={busy} className="arena-btn" onClick={()=>act("request",player.id)}>Send friend request</button></div>}
 <h2 className="text-xl font-bold">Requests</h2>{friends.filter(f=>f.status==="pending").map(f=><div key={f.id} className="border-t border-arena-line py-3 flex flex-wrap gap-3 items-center"><span className="break-all">{name(f.sender===user.id?f.recipient:f.sender)}</span>{f.recipient===user.id?<button disabled={busy} className="arena-btn" onClick={()=>act("accept",f.id)}>Accept</button>:<span>Request sent</span>}<button disabled={busy} className="arena-btn" onClick={()=>act("remove",f.id)}>{f.sender===user.id?"Cancel":"Decline"}</button></div>)}</section>
 <section className="arena-card space-y-4"><h2 className="text-xl font-bold">Game invitations ({invites.length})</h2>{!invites.length&&<p className="text-arena-muted">Your friends’ invitations will appear here.</p>}{invites.map(i=><div key={i.id} className="border-t border-arena-line py-3 space-y-2"><p>{name(i.sender)} invited you to play</p><p className="font-mono font-bold">{i.code}</p><Link className="arena-btn arena-btn-primary" href={`/${i.kind}?code=${i.code}`}>Join game</Link><button disabled={busy} className="arena-btn" onClick={()=>act("dismiss",i.id)}>Dismiss</button></div>)}</section></div>
 <section className="arena-card space-y-4"><h2 className="text-xl font-bold">My friends ({friends.filter(f=>f.status==="accepted").length})</h2><p className="text-arena-muted">Create a room or challenge, then enter its code to invite a friend.</p><div className="flex flex-wrap gap-3"><select aria-label="Invitation game mode" className="arena-input" value={kind} onChange={e=>setKind(e.target.value)}><option value="challenge">Challenge</option><option value="multiplayer">1v1 Buzzer</option></select><input aria-label="Game code" className="arena-input" maxLength={8} placeholder="GAME CODE" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></div>{friends.filter(f=>f.status==="accepted").map(f=><div key={f.id} className="flex flex-wrap items-center gap-3 border-t border-arena-line py-3"><span className="flex-1 break-all">{name(f.sender===user.id?f.recipient:f.sender)}</span><button className="arena-btn arena-btn-primary" disabled={busy||!code} onClick={()=>act("invite",f.sender===user.id?f.recipient:f.sender)}>Invite to play</button><button className="arena-btn" disabled={busy} onClick={()=>act("remove",f.id)}>Remove</button></div>)}</section></main>;
}
