"use client";
import {useCallback,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
type Row={id:string;display_name?:string;code?:string;title?:string;status?:string;creator_name?:string;created_at:string};
type Group={total:number;rows:Row[]};
type Data={timestamp:string;users:Group;rooms:Group;challenges:Group};
export default function Admin(){
 const router=useRouter();const [token,setToken]=useState(""),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[tab,setTab]=useState<"users"|"rooms"|"challenges">("users"),[page,setPage]=useState(0);
 useEffect(()=>{const t=sessionStorage.getItem("arena_admin_token");if(!t){router.replace("/admin/login");return;}setToken(t);},[router]);
 const load=useCallback(async()=>{if(!token)return;try{const r=await fetch(`/api/admin/stats?page=${page}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(r.status===401){router.replace("/admin/login");return;}const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError("");}catch(e){setError(e instanceof Error?e.message:"Refresh failed");}},[token,page,router]);
 useEffect(()=>{void load();const t=setInterval(load,5000);return()=>clearInterval(t);},[load]);
 return <main className="arena-container py-10 space-y-6"><div className="flex flex-wrap justify-between gap-4"><h1 className="text-3xl font-bold">Arena admin</h1><Link href="/" className="arena-btn">Back to Arena</Link></div><p className="text-arena-muted">Database records · Refreshes every 5 seconds · Times shown in your device’s timezone</p><p role="status">{error || (data?`Last synced ${new Date(data.timestamp).toLocaleString()}`:"Loading…")}</p><div className="grid sm:grid-cols-3 gap-4">{(["users","rooms","challenges"] as const).map(t=><button key={t} aria-pressed={tab===t} className="arena-card text-left" onClick={()=>{setTab(t);setPage(0);}}><span className="capitalize">{t}</span><strong className="block text-4xl mt-3">{data?data[t].total:"—"}</strong></button>)}</div><section className="arena-card overflow-x-auto"><h2 className="capitalize text-xl font-bold mb-4">{tab}</h2><table className="w-full text-sm text-left"><thead><tr><th className="p-3">{tab==="users"?"Name":"Code / title"}</th><th className="p-3">{tab==="users"?"User ID":tab==="rooms"?"Status":"Creator"}</th><th className="p-3">Created date & time</th></tr></thead><tbody>{data?.[tab].rows.map(r=><tr key={r.id} className="border-t border-arena-line"><td className="p-3">{r.display_name||r.title||r.code||"Unnamed"}{r.title&&<span className="block font-mono">{r.code}</span>}</td><td className="p-3 break-all">{tab==="users"?r.id:r.status||r.creator_name||"—"}</td><td className="p-3 whitespace-nowrap"><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleString()}</time></td></tr>)}</tbody></table>{data&&!data[tab].rows.length&&<p>No records on this page.</p>}</section><div className="flex gap-3"><button className="arena-btn" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="py-3">Page {page+1}</span><button className="arena-btn" disabled={!data||(page+1)*50>=data[tab].total} onClick={()=>setPage(p=>p+1)}>Next</button><button className="arena-btn" onClick={()=>void load()}>Refresh now</button></div></main>;
}
